database:
    server: 10.35.83.61:1433
    user: PowerCalc
    password: Power@1433
    database: PowerCalcFor46
    source: file://scripts

middlewares:
    authentication:
        enable: true
    authorization:
        enable: false
        policy: authpolicy.csv
        model: authmodel.conf
    log:
        enable: false
log:
    level: debug
    formatter: text
    prefix: pcrs
