database:
    url: 123
    port: 9090
middlewares:
    jwt:
        enable: true
    log:
        enable: false
    authorization:
        enable: false
        policy: authpolicy.csv
        model: authmodel.conf
