database:
    url: 123
    port: 9090
middlewares:
    authentication:
        enable: true
    authorization:
        enable: false
        policy: authpolicy.csv
        model: authmodel.conf
    log:
        enable: false
