databaseURI: 123
port: 9090
Hacker: true
iso8601: 2001-12-14t21:59:43.10-05:00 
bbcyyb:
  aaa:
    xxx: 22.98
  bbb:
  - mm
  - nn
  ccc:
    ddd:
    - 111
    - 222
    - 333
Name: steve
Hobbies:
- stkateboarding
- snowboarding
- go
clothing:
  jacket: leather
  trousers: denim
age: 35
eyes: brown
beard: true

jwtSecret: DellEMC

timeOffset: 168 # Hour