db:
    server: 10.35.83.61:1433
    user: PowerCalc
    password: Power@1433
    database: PowerCalcFor46
    source: file://scripts
middleware:
    authentication:
        enable: true
    authorization:
        enable: true
    errorHandler:
        enable: true
pkg:
    authorizer:
        policy: authpolicy.csv
        model: authmodel.conf
    log:
        level: debug
        formatter: text
        prefix: pcrs
        filename: pcrs.log
