// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package apis

import (
	"github.com/bbcyyb/pcrs/apis/article"
	"github.com/bbcyyb/pcrs/apis/misc"
	"github.com/bbcyyb/pcrs/pkg/jwt"
)

// Injectors from wire.go:

func initializeMisc() (*misc.MiscController, error) {
	iJwtGenerator := jwt.NewJwtGenerator()
	iService := misc.NewMiscService(iJwtGenerator)
	miscController := misc.NewMiscController(iService)
	return miscController, nil
}

func initializeArticle() (*article.ArticleController, error) {
	iRepository := article.NewArticleRepository()
	iService := article.NewArticleService(iRepository)
	articleController := article.NewArticleController(iService)
	return articleController, nil
}
